replicaCount: 1
#image pull
image:
  repository: 
  tag: latest
resources:
  requests:
    cpu: "100m" #50 milli cores (0.05 CPU)
    memory: "64Mi" 
  limits:
    cpu: "400m"
    memory: "256Mi"
  
  
service:
  name: 
  namespace: 

route:
  name: 

secret:   
